name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: git clone https://github.com/Wopslang/Wops.git cd Wops
    - name: make
      run: make
    - name: run
      run: ./test < ci-test.txt
    - name: clear
      run: make clean cd .. rm -rf Wops
