name: Wopslang CI

on:
  push:
    branches: [ main, lab ]
  pull_request:
    branches: [ main, lab ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: bash build.sh; mv Wopslang test/
    - name: configure
      run: cd test; ls
    - name: run
      run: ./Wopslang ci-test.wops debug < in
    - name: clear
      run: rm Wopslang
