name: Wopslang CI

on:
  push:
    branches: [ main, lab ]
  pull_request:
    branches: [ main, lab ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: configure
      run: sudo apt-get install tree; ls;
    - name: make
      run: bash build.sh; mv Wopslang test/; 
    - name: run
      run: cd test; tree; cat in | ./Wopslang ci-test.wops debug
    - name: clear
      run: rm test/Wopslang
