name: Wopslang CI

on:
  push:
    branches: [ main, lab ]
  pull_request:
    branches: [ main, lab ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: bash build.sh
    - name: configure 1
      run: mv Wopslang test/
    - name: configure 2
      run: cd test
    - name: run
      run: ./Wopslang ci-test debug < in
    - name: clear
      run: rm Wopslang
